/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import metadata from './metadata';
import person from './person';
import word from './word';

/**
 * The locale data for the `sl_SI` locale.
 *
 * - Language: Slovenian (Slovenia)
 * - Endonym: Slovensko (Slovenia)
 */
const sl_SI: LocaleDefinition = {
  metadata,
  person,
  word,
};

export default sl_SI;
